export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS'
export const CREATE_CONFIG_SUCCESS = 'CREATE_CONFIG_SUCCESS'
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS'
export const DELETE_CONFIG_SUCCESS = 'DELETE_CONFIG_SUCCESS'
