export const FETCH_VEHICLE_SUCCESS = 'FETCH_VEHICLE_SUCCESS'
export const FETCH_MONTHLY_FIXED_VEHICLE_SUCCESS = 'FETCH_MONTHLY_FIXED_VEHICLE_SUCCESS'
export const EMPTY_VEHICLE_LIST = 'EMPTY_VEHICLE_LIST'
